 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: myapp
   labels:
     app: myapp
 spec:
   selector:
     matchLabels:
       app: myapp
   template:
     metadata:
       labels:
         app: myapp
     spec:
       containers:
       - image: myapp:somerevision
         name: myappm
         volumeMounts:
         - mountPath: /data/service/config
           name: config
       volumes:
       - configMap:
           name: myapp
         name: config

